### ISSUE TITLE
Table name

### ISSUE THREAD

**Issue by akalongman** [telkins/laravel-dag-manager#12]
Imho the table name should be configurable

**Comment by telkins** [comment]
Agreed.  I am happy to add this, but I can't say for sure when I might have time.  Feel free to submit any PRs in the meantime.

(I'll post again here if I start to work on it and would ask you to do the same....so we don't work unnecessarily. 🤓 )

**Comment by telkins** [comment]
FYI...as you likely already know, the table name's now configurable....thx to your submission...!  🤓
